export const SERVICES = [
  {
    id: 'ai-ml',
    code: '01',
    tag: 'AI · ML · Agents',
    title: 'AI & ML',
    subtitle: 'Generative AI · Agents · MLOps',
    body:
      'Enterprise AI solutions engineered to automate workflows, optimize operations, and accelerate business growth.',
    image: '/AI_bg.jpg',
    accent: '#90eb61',
    description:
      'We design, build, and operationalize enterprise-grade AI and ML systems — generative copilots, autonomous agents, computer vision, NLP, predictive analytics, and the MLOps backbone that keeps them reliable in production.',
    features: [
      'Generative AI & enterprise copilots',
      'Autonomous AI agent systems',
      'Natural Language Processing',
      'Predictive analytics & forecasting',
      'Computer vision & multimodal AI',
      'MLOps & AI engineering',
    ],
    benefits: [
      '↑ Productivity with AI copilots & agents',
      '↓ Manual effort via intelligent automation',
      '↑ Forecast accuracy with ML models',
      '↑ Speed-to-value with production MLOps',
      '↑ Trust with governed, auditable AI',
    ],
    timeline: [
      { phase: 'Discover', body: 'Use-case mapping, data audit, AI feasibility & ROI.' },
      { phase: 'Prototype', body: 'Rapid LLM/ML PoC, evaluation, guardrails.' },
      { phase: 'Productionize', body: 'MLOps pipelines, observability, governance.' },
      { phase: 'Scale', body: 'Drift monitoring, retraining, FinOps & adoption.' },
    ],
    tech: ['OpenAI', 'Anthropic', 'LangChain', 'LangGraph', 'PyTorch', 'TensorFlow', 'Hugging Face', 'Vector DBs', 'Kubeflow', 'MLflow', 'Snowflake Cortex', 'Databricks'],
  },
  {
    id: 'salesforce',
    code: '02',
    tag: 'CRM · Cloud',
    title: 'Salesforce',
    subtitle: 'Sales · Service · Marketing',
    body:
      'Architect end-to-end Salesforce ecosystems engineered for scale, automation, and real-time intelligence.',
    image: '/salesforce_bg.jpg',
    accent: '#24baac',
    description:
      'We design and deliver Salesforce platforms that align Sales, Service, Marketing, and Experience Clouds into a single operating fabric — built to grow with you and intelligent by default.',
    features: [
      'Sales & Service Cloud architecture',
      'Experience Cloud journeys',
      'Apex & LWC engineering',
      'Einstein AI activation',
      'Composable integration patterns',
    ],
    benefits: [
      '↑ Pipeline conversion via unified data',
      '↓ Cycle time with intelligent automation',
      '↑ CSAT through omnichannel service',
      '↓ Total cost of ownership',
    ],
    timeline: [
      { phase: 'Discover', body: 'Stakeholder workshops, journey mapping, target architecture.' },
      { phase: 'Design', body: 'Solution blueprint, data model, integration patterns.' },
      { phase: 'Build', body: 'Agile delivery on a hardened DevOps backbone.' },
      { phase: 'Launch', body: 'Pilot, hypercare, knowledge transfer, optimization.' },
    ],
    tech: ['Sales Cloud', 'Service Cloud', 'Apex', 'LWC', 'Einstein', 'Flow', 'Data Cloud'],
  },
  {
    id: 'snowflake',
    code: '03',
    tag: 'Data Cloud · AI',
    title: 'Snowflake',
    subtitle: 'Warehouse · Sharing · ML',
    body:
      'Modern cloud data warehousing, secure data sharing, and scalable AI-powered analytics with Snowflake Data Cloud.',
    image: '/snowflake_bg.jpg',
    accent: '#24baac',
    description:
      'Genufy helps you unlock the full potential of the Snowflake Data Cloud — from migration and implementation to data engineering, sharing, and AI-powered analytics on a scalable, secure foundation.',
    features: [
      'Modern Data Warehousing',
      'Secure Data Sharing & Marketplace',
      'Snowpark for Python / Java / Scala',
      'Streamlit Data Apps',
      'Cross-cloud, cross-region replication',
    ],
    benefits: [
      '↑ Performance with elastic compute',
      '↓ Cost with separate compute & storage',
      '↑ Collaboration via live sharing',
      '↑ ML velocity with Snowpark',
    ],
    timeline: [
      { phase: 'Assess', body: 'Workload audit, target architecture, business case.' },
      { phase: 'Foundation', body: 'Account topology, RBAC, networking, governance.' },
      { phase: 'Build', body: 'Pipelines, models, Snowpark apps, dashboards.' },
      { phase: 'Operate', body: 'Observability, FinOps, continuous tuning.' },
    ],
    tech: ['Snowflake', 'Snowpark', 'Streamlit', 'dbt', 'Iceberg', 'Cortex'],
  },
  {
    id: 'informatica',
    code: '04',
    tag: 'Data · iPaaS · MDM',
    title: 'Informatica',
    subtitle: 'Integration · Governance · Cloud',
    body:
      'AI-powered data integration, governance, MDM, and cloud application connectivity for modern enterprises.',
    image: '/informatica_bg.jpg',
    accent: '#90eb61',
    description:
      'Informatica empowers organizations to connect, cleanse, govern, and manage data across cloud, hybrid, and on-premise environments — turning trusted data into intelligent business outcomes.',
    features: [
      'Cloud Data Integration (ETL / ELT)',
      'Data Quality & Governance',
      'Master Data Management (MDM)',
      'Data Catalog & Lineage',
      'Application Integration (iPaaS)',
    ],
    benefits: [
      '↑ Data trust with AI-driven quality',
      '↓ Risk through governance & lineage',
      '↑ Speed-to-insight with real-time pipelines',
      '↑ Compliance with built-in privacy controls',
    ],
    timeline: [
      { phase: 'Assess', body: 'Source inventory, data quality audit, target architecture.' },
      { phase: 'Foundation', body: 'IDMC org topology, security, runtime environments.' },
      { phase: 'Build', body: 'Pipelines, MDM, catalog, governance & iPaaS flows.' },
      { phase: 'Operate', body: 'Monitoring, FinOps, continuous CLAIRE adoption.' },
    ],
    tech: ['IDMC', 'CLAIRE', 'Cloud Data Integration', 'MDM', 'Axon', 'Data Quality', 'EDC'],
  },
  {
    id: 'devops',
    code: '05',
    tag: 'Cloud · Reliability',
    title: 'DevOps',
    subtitle: 'Platform · SRE · FinOps',
    body:
      'Production discipline as a feature — pipelines, infrastructure as code, and observability that make shipping fast feel safe.',
    image: '/DevOps_bg.jpg',
    accent: '#24baac',
    description:
      'We build platform layers that compound — golden paths for developers, infrastructure-as-code, SRE playbooks, and the kind of observability that turns 3am pages into one-line fixes.',
    features: [
      'Kubernetes & service meshes',
      'Terraform & Pulumi IaC',
      'GitHub Actions / GitLab CI',
      'Observability (OTEL, Grafana)',
      'SRE & FinOps playbooks',
    ],
    benefits: [
      '↑ Deploy frequency with safe pipelines',
      '↓ MTTR via tracing & runbooks',
      '↓ Cloud spend through FinOps loops',
      '↑ Developer experience & velocity',
    ],
    timeline: [
      { phase: 'Assess', body: 'Maturity model, risk map, target platform.' },
      { phase: 'Platform', body: 'IaC, golden paths, secrets, environments.' },
      { phase: 'Observe', body: 'Tracing, SLOs, alerting, on-call rituals.' },
      { phase: 'Optimize', body: 'FinOps, autoscaling, performance baselines.' },
    ],
    tech: ['Kubernetes', 'Terraform', 'ArgoCD', 'GitHub Actions', 'Grafana', 'OpenTelemetry'],
  },
  {
    id: 'mulesoft',
    code: '06',
    tag: 'API · Integration',
    title: 'MuleSoft',
    subtitle: 'API-Led · Anypoint',
    body:
      'API-led connectivity that unifies CRMs, ERPs, and custom systems into a scalable, resilient digital backbone.',
    image: '/MuleSoft_bg.jpg',
    accent: '#90eb61',
    description:
      'We design and operate MuleSoft estates that unlock the enterprise — clean API contracts, event-driven flows, and governance that scales as fast as the business does.',
    features: [
      'Anypoint Platform architecture',
      'API-led design (System / Process / Experience)',
      'Event-driven integration',
      'Legacy system modernization',
      'API governance & catalog',
    ],
    benefits: [
      '↑ Reuse with composable APIs',
      '↓ Integration cost via system layer',
      '↑ Resilience through event flows',
      '↑ Time-to-market on new journeys',
    ],
    timeline: [
      { phase: 'Audit', body: 'Capability map, current vs. target integration.' },
      { phase: 'Design', body: 'API taxonomy, contracts, error & retry patterns.' },
      { phase: 'Build', body: 'Anypoint flows, CI/CD, monitoring, catalog.' },
      { phase: 'Govern', body: 'Lifecycle, versioning, SLAs, FinOps.' },
    ],
    tech: ['MuleSoft', 'Anypoint', 'DataWeave', 'Kafka', 'OAuth2', 'OpenAPI'],
  },
  {
    id: 'pega',
    code: '07',
    tag: 'BPM · CRM · Decisioning',
    title: 'Pega',
    subtitle: 'BPM · CRM · AI · RPA',
    body:
      'Pega-based BPM, CRM, AI decisioning, and RPA - streamline processes and elevate customer engagement.',
    image: '/pega_bg.jpg',
    accent: '#24baac',
    description:
      'At Genufy, we specialize in delivering Pega-based solutions that streamline processes, improve operational efficiency, and elevate customer engagement. From Pega BPM and CRM to AI decisioning and RPA, we design and integrate scalable Pega systems that accelerate business outcomes, automate workflows, and provide a strong foundation for future growth.',
    features: [
      'Pega BPM workflow automation',
      'Pega CRM & case management',
      'AI-powered real-time decisioning',
      'Robotic Process Automation (RPA)',
      'Enterprise system integrations',
    ],
    benefits: [
      '↑ Operational efficiency through automation',
      '↑ Customer satisfaction with omnichannel CX',
      '↓ Manual effort with intelligent bots',
      '↑ Decision velocity with adaptive AI',
      '↑ Scalability with reusable Pega assets',
    ],
    timeline: [
      { phase: 'Discover', body: 'Process audit, journey mapping, target architecture.' },
      { phase: 'Design', body: 'Case types, data model, decisioning strategy, RPA scope.' },
      { phase: 'Build', body: 'Pega apps, AI rules, RPA bots, integrations, testing.' },
      { phase: 'Operate', body: 'Hypercare, optimization, continuous improvement.' },
    ],
    tech: ['Pega Platform', 'Pega BPM', 'Pega CRM', 'Pega Customer Decision Hub', 'Pega RPA', 'Pega Constellation'],
  },
  {
    id: 'web',
    code: '08',
    tag: 'Interfaces · UX',
    title: 'Web Development',
    subtitle: 'React · Next.js · WebGL',
    body:
      'Award-calibre digital products - performance-first, motion-rich, and built to convert from the first frame.',
    image: '/web_bg.png',
    accent: '#24baac',
    description:
      'Premium web experiences engineered on modern stacks - every pixel, transition, and edge case earns its place. From design systems to WebGL, we ship sites worth stopping for.',
    features: [
      'React & Next.js architecture',
      'Edge rendering & ISR',
      'Design systems at scale',
      'Headless CMS integration',
      'WebGL & motion craft',
    ],
    benefits: [
      '↑ Conversion via fast LCP & smooth UX',
      '↑ Brand affinity through motion craft',
      '↓ Build time with reusable design system',
      '↑ SEO from edge-first rendering',
    ],
    timeline: [
      { phase: 'Strategy', body: 'Audience research, content model, IA blueprint.' },
      { phase: 'Design', body: 'Visual language, motion system, prototypes.' },
      { phase: 'Engineer', body: 'Edge-first delivery, instrumentation, a11y.' },
      { phase: 'Iterate', body: 'CRO loops, content velocity, performance budget.' },
    ],
    tech: ['React', 'Next.js', 'TypeScript', 'Tailwind', 'Framer Motion', 'GSAP', 'Three.js'],
  },
];
