/* AUTO-GENERATED by scripts/gen-clients.mjs - do not edit by hand.
   Regenerated automatically before `dev` and `build`. */
export const CLIENTS = [
  {
    "src": "/clients/abbvie.webp",
    "label": "Abbvie"
  },
  {
    "src": "/clients/alcority.webp",
    "label": "Alcority"
  },
  {
    "src": "/clients/Cedars.webp",
    "label": "Cedars"
  },
  {
    "src": "/clients/cigna.webp",
    "label": "Cigna"
  },
  {
    "src": "/clients/comcast.webp",
    "label": "Comcast"
  },
  {
    "src": "/clients/cree.webp",
    "label": "Cree"
  },
  {
    "src": "/clients/edf.webp",
    "label": "Edf"
  },
  {
    "src": "/clients/FHL.webp",
    "label": "FHL"
  },
  {
    "src": "/clients/Hilton.webp",
    "label": "Hilton"
  },
  {
    "src": "/clients/Ncaa.webp",
    "label": "Ncaa"
  },
  {
    "src": "/clients/smbc.webp",
    "label": "Smbc"
  },
  {
    "src": "/clients/vitalant.webp",
    "label": "Vitalant"
  },
  {
    "src": "/clients/wex.webp",
    "label": "Wex"
  },
  {
    "src": "/clients/Willscot.webp",
    "label": "Willscot"
  },
  {
    "src": "/clients/woodstream.webp",
    "label": "Woodstream"
  },
  {
    "src": "/clients/worldpay.webp",
    "label": "Worldpay"
  }
];
