/* AUTO-GENERATED by scripts/gen-clients.mjs - do not edit by hand.
   Regenerated automatically before `dev` and `build`. */
export const CLIENTS = [
  {
    "src": "/clients/abbvie.png",
    "label": "Abbvie"
  },
  {
    "src": "/clients/alcority.png",
    "label": "Alcority"
  },
  {
    "src": "/clients/Cedars.png",
    "label": "Cedars"
  },
  {
    "src": "/clients/cigna.png",
    "label": "Cigna"
  },
  {
    "src": "/clients/comcast.png",
    "label": "Comcast"
  },
  {
    "src": "/clients/cree.png",
    "label": "Cree"
  },
  {
    "src": "/clients/edf.png",
    "label": "Edf"
  },
  {
    "src": "/clients/FHL.png",
    "label": "FHL"
  },
  {
    "src": "/clients/Hilton.png",
    "label": "Hilton"
  },
  {
    "src": "/clients/Ncaa.png",
    "label": "Ncaa"
  },
  {
    "src": "/clients/smbc.webp",
    "label": "Smbc"
  },
  {
    "src": "/clients/vitalant.png",
    "label": "Vitalant"
  },
  {
    "src": "/clients/wex.png",
    "label": "Wex"
  },
  {
    "src": "/clients/Willscot.png",
    "label": "Willscot"
  },
  {
    "src": "/clients/woodstream.png",
    "label": "Woodstream"
  },
  {
    "src": "/clients/worldpay.png",
    "label": "Worldpay"
  }
];
