/* Scans public/clients/ and writes src/components/clientsManifest.js.
 *
 * Replaces Vite's import.meta.glob (unsupported in Next). Runs automatically
 * before `dev` and `build` via package.json scripts, so dropping a new logo
 * into public/clients/ still makes it appear in the Trusted Clients marquee —
 * name and order derived from the filename, exactly as before.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const clientsDir = join(root, 'public', 'clients');
const outFile = join(root, 'src', 'components', 'clientsManifest.js');

const IMAGE_RE = /\.(png|jpe?g|webp|svg|avif)$/i;

function labelFromPath(file) {
  return file
    .replace(/\.[^.]+$/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

let files = [];
try {
  files = readdirSync(clientsDir).filter((f) => IMAGE_RE.test(f));
} catch {
  files = [];
}

const clients = files
  .map((file) => ({ src: `/clients/${file}`, label: labelFromPath(file) }))
  .sort((a, b) => a.label.localeCompare(b.label));

const banner =
  '/* AUTO-GENERATED by scripts/gen-clients.mjs — do not edit by hand.\n' +
  '   Regenerated automatically before `dev` and `build`. */\n';

writeFileSync(
  outFile,
  `${banner}export const CLIENTS = ${JSON.stringify(clients, null, 2)};\n`
);

console.log(`[gen-clients] wrote ${clients.length} client logos to clientsManifest.js`);
